# https://github.com/SlinkyProject/slurm-operator/blob/main/helm/slurm/values.yaml
accounting:
  enabled: true

loginsets:
  slinky:
    enabled: true
    replicas: 1
    rootSshAuthorizedKeys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICA5P5hkONzI+dltZ7NGaGOfm4SNwozHk5E2Xj60WR2o explorerray
    service:
      spec:
        type: NodePort
        port: 22
        nodePort: 32222
